package com.studenttracker.model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * RecentActivity - Model class representing a logged system activity.
 * 
 * <p><b>Purpose:</b> Track all significant actions in the system for audit trail
 * and dashboard display.</p>
 * 
 * <p><b>Activity Types:</b></p>
 * <ul>
 *   <li>LESSON_CREATED - New lesson created</li>
 *   <li>STUDENT_REGISTERED - New student registered</li>
 *   <li>STUDENT_ARCHIVED - Student archived (3 absences or other reason)</li>
 *   <li>STUDENT_RESTORED - Archived student restored to active</li>
 *   <li>WARNING_GENERATED - Warning created for student</li>
 *   <li>WARNING_RESOLVED - Warning marked as resolved</li>
 *   <li>MISSION_ASSIGNED - Mission assigned to user</li>
 *   <li>MISSION_COMPLETED - Mission marked complete</li>
 *   <li>QUIZ_GRADED - Quiz grading completed</li>
 *   <li>ATTENDANCE_RECORDED - Attendance batch completed</li>
 *   <li>HOMEWORK_RECORDED - Homework batch completed</li>
 *   <li>UPDATE_REQUEST_SUBMITTED - Update request submitted</li>
 *   <li>UPDATE_REQUEST_APPROVED - Update request approved</li>
 *   <li>UPDATE_REQUEST_REJECTED - Update request rejected</li>
 * </ul>
 * 
 * <p><b>Usage Example - Creating Activity:</b></p>
 * <pre>
 * RecentActivity activity = new RecentActivity(
 *     "LESSON_CREATED",
 *     "Lesson 48 created by Ahmed",
 *     "LESSON",
 *     48,
 *     1
 * );
 * </pre>
 * 
 * <p><b>Usage Example - Reading from Database:</b></p>
 * <pre>
 * RecentActivity activity = new RecentActivity(
 *     1,                              // activityId
 *     "LESSON_CREATED",               // activityType
 *     "Lesson 48 created",            // description
 *     "LESSON",                       // entityType
 *     48,                             // entityId
 *     1,                              // performedBy
 *     LocalDateTime.now()             // createdAt
 * );
 * </pre>
 * 
 * @author fasee7System
 * @version 1.0.0
 * @since 2026-01-28
 */
public class RecentActivity {
    
    // ==================== CONSTANTS ====================
    
    /**
     * Date-time formatter for display (e.g., "Jan 28, 14:30")
     */
    private static final DateTimeFormatter DISPLAY_FORMATTER = 
        DateTimeFormatter.ofPattern("MMM dd, HH:mm");
    
    /**
     * Date-time formatter for time only (e.g., "14:30")
     */
    private static final DateTimeFormatter TIME_FORMATTER = 
        DateTimeFormatter.ofPattern("HH:mm");
    
    // ==================== FIELDS ====================
    
    /**
     * Unique identifier for the activity (auto-generated by database).
     */
    private Integer activityId;
    
    /**
     * Type of activity (e.g., "LESSON_CREATED", "STUDENT_REGISTERED").
     * Used for filtering and categorization.
     */
    private String activityType;
    
    /**
     * Human-readable description of the activity.
     * Example: "Lesson 48 created by Ahmed Admin"
     */
    private String activityDescription;
    
    /**
     * Type of entity involved (e.g., "LESSON", "STUDENT", "WARNING").
     * Optional - may be null for system-wide activities.
     */
    private String entityType;
    
    /**
     * ID of the entity involved (e.g., lesson_id, student_id).
     * Optional - may be null for system-wide activities.
     */
    private Integer entityId;
    
    /**
     * User ID who performed the action.
     * Optional - may be null for system-generated activities.
     */
    private Integer performedBy;
    
    /**
     * Timestamp when the activity occurred.
     * Auto-generated by database on insert.
     */
    private LocalDateTime createdAt;
    
    // ==================== CONSTRUCTORS ====================
    
    /**
     * Default constructor (required for frameworks/reflection).
     */
    public RecentActivity() {
        // Empty constructor
    }
    
    /**
     * Constructor for creating new activity (before database insert).
     * Used when logging activities from service layer.
     * 
     * @param activityType Type of activity
     * @param activityDescription Human-readable description
     * @param entityType Type of entity involved (can be null)
     * @param entityId ID of entity involved (can be null)
     * @param performedBy User ID who performed action (can be null for system)
     */
    public RecentActivity(String activityType, String activityDescription, 
                         String entityType, Integer entityId, Integer performedBy) {
        this.activityType = activityType;
        this.activityDescription = activityDescription;
        this.entityType = entityType;
        this.entityId = entityId;
        this.performedBy = performedBy;
        // createdAt will be set by database
    }
    
    /**
     * Full constructor (used by DAO when reading from database).
     * All fields are populated including auto-generated ones.
     * 
     * @param activityId Auto-generated activity ID
     * @param activityType Type of activity
     * @param activityDescription Human-readable description
     * @param entityType Type of entity involved
     * @param entityId ID of entity involved
     * @param performedBy User ID who performed action
     * @param createdAt Timestamp from database
     */
    public RecentActivity(Integer activityId, String activityType, 
                         String activityDescription, String entityType, 
                         Integer entityId, Integer performedBy, 
                         LocalDateTime createdAt) {
        this.activityId = activityId;
        this.activityType = activityType;
        this.activityDescription = activityDescription;
        this.entityType = entityType;
        this.entityId = entityId;
        this.performedBy = performedBy;
        this.createdAt = createdAt;
    }
    
    // ==================== GETTERS AND SETTERS ====================
    
    /**
     * Gets the activity ID.
     * @return the activity ID (auto-generated)
     */
    public Integer getActivityId() {
        return activityId;
    }
    
    /**
     * Sets the activity ID.
     * Typically only used by DAO when reading from database.
     * @param activityId the activity ID
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
    
    /**
     * Gets the activity type.
     * @return the activity type (e.g., "LESSON_CREATED")
     */
    public String getActivityType() {
        return activityType;
    }
    
    /**
     * Sets the activity type.
     * @param activityType the activity type
     */
    public void setActivityType(String activityType) {
        this.activityType = activityType;
    }
    
    /**
     * Gets the activity description.
     * @return the human-readable description
     */
    public String getActivityDescription() {
        return activityDescription;
    }
    
    /**
     * Sets the activity description.
     * @param activityDescription the description
     */
    public void setActivityDescription(String activityDescription) {
        this.activityDescription = activityDescription;
    }
    
    /**
     * Gets the entity type.
     * @return the entity type (e.g., "LESSON", "STUDENT"), or null
     */
    public String getEntityType() {
        return entityType;
    }
    
    /**
     * Sets the entity type.
     * @param entityType the entity type
     */
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }
    
    /**
     * Gets the entity ID.
     * @return the entity ID, or null
     */
    public Integer getEntityId() {
        return entityId;
    }
    
    /**
     * Sets the entity ID.
     * @param entityId the entity ID
     */
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }
    
    /**
     * Gets the user ID who performed the action.
     * @return the user ID, or null for system-generated activities
     */
    public Integer getPerformedBy() {
        return performedBy;
    }
    
    /**
     * Sets the user ID who performed the action.
     * @param performedBy the user ID
     */
    public void setPerformedBy(Integer performedBy) {
        this.performedBy = performedBy;
    }
    
    /**
     * Gets the timestamp when activity occurred.
     * @return the creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
    
    /**
     * Sets the timestamp when activity occurred.
     * Typically only used by DAO when reading from database.
     * @param createdAt the creation timestamp
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
    
    // ==================== HELPER METHODS ====================
    
    /**
     * Formats the creation timestamp for display.
     * 
     * @return formatted date-time string (e.g., "Jan 28, 14:30")
     */
    public String getFormattedDateTime() {
        if (createdAt == null) {
            return "N/A";
        }
        return createdAt.format(DISPLAY_FORMATTER);
    }
    
    /**
     * Formats just the time portion for display.
     * 
     * @return formatted time string (e.g., "14:30")
     */
    public String getFormattedTime() {
        if (createdAt == null) {
            return "N/A";
        }
        return createdAt.format(TIME_FORMATTER);
    }
    
    /**
     * Checks if this activity has an associated entity.
     * 
     * @return true if entityType and entityId are both non-null
     */
    public boolean hasEntity() {
        return entityType != null && entityId != null;
    }
    
    /**
     * Checks if this activity was performed by a user.
     * 
     * @return true if performedBy is non-null
     */
    public boolean hasPerformer() {
        return performedBy != null;
    }
    
    /**
     * Gets a display-friendly summary of the activity.
     * Includes description and timestamp.
     * 
     * @return summary string (e.g., "Lesson 48 created (Jan 28, 14:30)")
     */
    public String getSummary() {
        return activityDescription + " (" + getFormattedDateTime() + ")";
    }
    
    // ==================== OBJECT METHODS ====================
    
    /**
     * Returns a string representation of this activity.
     * Useful for debugging and logging.
     * 
     * @return string representation
     */
    @Override
    public String toString() {
        return "RecentActivity{" +
                "activityId=" + activityId +
                ", activityType='" + activityType + '\'' +
                ", description='" + activityDescription + '\'' +
                ", entityType='" + entityType + '\'' +
                ", entityId=" + entityId +
                ", performedBy=" + performedBy +
                ", createdAt=" + createdAt +
                '}';
    }
    
    /**
     * Checks equality based on activityId.
     * Two activities are equal if they have the same ID.
     * 
     * @param o object to compare
     * @return true if equal
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        
        RecentActivity that = (RecentActivity) o;
        
        return activityId != null && activityId.equals(that.activityId);
    }
    
    /**
     * Hash code based on activityId.
     * 
     * @return hash code
     */
    @Override
    public int hashCode() {
        return activityId != null ? activityId.hashCode() : 0;
    }
}