package com.studenttracker.dao;

import com.studenttracker.model.RecentActivity;

import java.util.List;

/**
 * Data Access Object interface for RecentActivity entity operations.
 * 
 * <p><b>Purpose:</b> Provides database operations for the recent_activities table.</p>
 * 
 * <p><b>Responsibilities:</b></p>
 * <ul>
 *   <li>Insert new activities into the database</li>
 *   <li>Retrieve recent activities (with limit)</li>
 *   <li>Filter activities by type</li>
 *   <li>Clean up old activities (retention policy)</li>
 * </ul>
 * 
 * <p><b>Usage Example:</b></p>
 * <pre>
 * RecentActivityDAO activityDAO = ServiceLocator.getInstance().getClassDAO(RecentActivityDAOImpl.class);
 * 
 * // Insert new activity
 * RecentActivity activity = new RecentActivity(
 *     "LESSON_CREATED",
 *     "Lesson 48 created by Ahmed",
 *     "LESSON",
 *     48,
 *     1
 * );
 * int activityId = activityDAO.insert(activity);
 * 
 * // Get recent 20 activities
 * List<RecentActivity> recent = activityDAO.getRecent(20);
 * 
 * // Get only lesson activities
 * List<RecentActivity> lessons = activityDAO.getByType("LESSON_CREATED", 10);
 * 
 * // Cleanup old activities (30+ days)
 * int deleted = activityDAO.deleteOlderThan(30);
 * </pre>
 * 
 * @author fasee7System
 * @version 1.0.0
 * @since 2026-01-28
 */
public interface RecentActivityDAO {
    
    /**
     * Inserts a new activity into the database.
     * The activity_id and created_at fields are auto-generated by the database.
     * 
     * @param activity The activity to insert (activityId and createdAt will be ignored)
     * @return The auto-generated activity ID
     * @throws com.studenttracker.exception.DAOException if database operation fails
     */
    int insert(RecentActivity activity);
    
    /**
     * Retrieves the most recent N activities from the database.
     * Results are ordered by created_at in descending order (newest first).
     * 
     * <p><b>Performance Note:</b> Uses index on created_at for fast retrieval.</p>
     * 
     * @param limit Maximum number of activities to retrieve (e.g., 20 for dashboard)
     * @return List of recent activities (may be empty, never null)
     * @throws com.studenttracker.exception.DAOException if database operation fails
     */
    List<RecentActivity> getRecent(int limit);
    
    /**
     * Retrieves activities of a specific type.
     * Results are ordered by created_at in descending order (newest first).
     * 
     * <p><b>Performance Note:</b> Uses index on activity_type for fast filtering.</p>
     * 
     * <p><b>Example Activity Types:</b></p>
     * <ul>
     *   <li>LESSON_CREATED</li>
     *   <li>STUDENT_REGISTERED</li>
     *   <li>WARNING_GENERATED</li>
     *   <li>MISSION_COMPLETED</li>
     * </ul>
     * 
     * @param activityType The type of activity to filter by
     * @param limit Maximum number of activities to retrieve
     * @return List of matching activities (may be empty, never null)
     * @throws com.studenttracker.exception.DAOException if database operation fails
     */
    List<RecentActivity> getByType(String activityType, int limit);
    
    /**
     * Deletes activities older than the specified number of days.
     * This is used for data retention and cleanup.
     * 
     * <p><b>Recommended Retention:</b> 30-90 days for dashboard activities</p>
     * 
     * <p><b>Example Usage:</b></p>
     * <pre>
     * // Delete activities older than 30 days
     * int deleted = activityDAO.deleteOlderThan(30);
     * logger.info("Cleaned up " + deleted + " old activities");
     * </pre>
     * 
     * @param days Number of days to keep (activities older than this are deleted)
     * @return Number of activities deleted
     * @throws com.studenttracker.exception.DAOException if database operation fails
     */
    int deleteOlderThan(int days);
}